variable "common_tags" {}
variable "region" {}
variable "account_name" {}
variable "transit_gw_name" {}
variable "cidr" {}
variable "asn" {}
variable "transit_eip" {}
variable "transit_ha_eip" {}
variable "vpc_id" {}
